import { GiftlySpace } from './types';

export const INITIAL_SPACES: GiftlySpace[] = [
  {
    id: 'christmas-wishlist-class-06-2026',
    title: "Christmas Wishlist Class '06 2026",
    tagline: 'Batchmates holiday exchange! Long-press or click any wish to prepare a gift or volunteer to share.',
    type: 'secret',
    occasion: 'Christmas / Secret Santa',
    organizerName: 'Noel',
    organizerKeyword: '19051905',
    currency: '$',
    createdAt: '2026-09-22T07:20:57.831Z',
    targetDate: '2026-12-25',
    participants: [
      {
        id: 'p-n2czl2t',
        name: 'Noel',
        keyword: '19051905',
        avatarColor: 'bg-[#5C1525]',
        isOrganizer: true,
        tagline: "Batch '06 • Tech, travel & EDC",
        joinedAt: '2026-09-22T07:20:57.831Z',
      },
      {
        id: 'p-sarah-m',
        name: 'Sarah Chen',
        keyword: 'daisy24',
        avatarColor: 'bg-[#741D30]',
        tagline: "Batch '06 • Coffee rituals & cozy reads",
        joinedAt: '2026-09-22T07:25:00.000Z',
      },
      {
        id: 'p-liam-k',
        name: 'Liam Vance',
        keyword: 'winter88',
        avatarColor: 'bg-[#3A5A40]',
        tagline: "Batch '06 • Trail running & mechanical keyboards",
        joinedAt: '2026-09-22T07:28:00.000Z',
      },
      {
        id: 'p-chloe-b',
        name: 'Chloe Bennett',
        keyword: 'velvet33',
        avatarColor: 'bg-[#8F5D38]',
        tagline: "Batch '06 • Pottery & vintage vinyl",
        joinedAt: '2026-09-22T07:30:00.000Z',
      },
    ],
    gifts: [
      {
        id: 'g-mcno-1',
        title: 'iPhone 16 Pro (Natural Titanium)',
        description: 'Upgrading my old work daily driver. Any help towards it is amazing!',
        price: 999,
        url: 'https://apple.com/iphone',
        category: 'Tech & Desk',
        addedBy: { id: 'p-n2czl2t', name: 'Noel' },
        forParticipantId: 'p-n2czl2t',
        createdAt: '2026-09-22T07:22:03.547Z',
        isGroupGift: true,
        status: 'sharing',
        reactions: [
          { id: 'r-1', type: 'excited', participantId: 'p-sarah-m', participantName: 'Sarah Chen' },
          { id: 'r-2', type: 'love', participantId: 'p-liam-k', participantName: 'Liam Vance' },
        ],
        contributions: [
          {
            id: 'c-1',
            participantId: 'p-sarah-m',
            participantName: 'Sarah Chen',
            amount: 100,
            note: 'Happy to contribute to the big group gift!',
            createdAt: '2026-09-22T07:35:00.000Z',
          },
          {
            id: 'c-2',
            participantId: 'p-liam-k',
            participantName: 'Liam Vance',
            amount: 75,
            note: 'Count me in for sharing!',
            createdAt: '2026-09-22T07:38:00.000Z',
          },
        ],
      },
      {
        id: 'g-mcno-2',
        title: 'Anker Magnetic Wireless Power Bank (10,000mAh)',
        description: 'Compact travel charger with kickstand.',
        price: 49,
        category: 'Tech & Desk',
        addedBy: { id: 'p-n2czl2t', name: 'Noel' },
        forParticipantId: 'p-n2czl2t',
        createdAt: '2026-09-22T07:24:00.000Z',
        isGroupGift: false,
        status: 'prepared',
        preparedBy: {
          participantId: 'p-chloe-b',
          participantName: 'Chloe Bennett',
          preparedAt: '2026-09-22T07:40:00.000Z',
          note: 'Already ordered this for you!',
        },
        reactions: [
          { id: 'r-3', type: 'check', participantId: 'p-chloe-b', participantName: 'Chloe Bennett' },
        ],
        contributions: [],
      },
      {
        id: 'g-mcno-3',
        title: 'Aer City Sling 2 (Black X-Pac)',
        description: 'Weatherproof everyday carry bag for commuting.',
        price: 99,
        url: 'https://aersf.com',
        category: 'Style & Accessories',
        addedBy: { id: 'p-n2czl2t', name: 'Noel' },
        forParticipantId: 'p-n2czl2t',
        createdAt: '2026-09-22T07:26:00.000Z',
        isGroupGift: false,
        status: 'open',
        reactions: [
          { id: 'r-4', type: 'idea', participantId: 'p-sarah-m', participantName: 'Sarah Chen' },
        ],
        contributions: [],
      },
      // Sarah's wishlist
      {
        id: 'g-sarah-1',
        title: 'Fellow Ode Gen 2 Coffee Grinder (Matte White)',
        description: 'Quiet flat burr grinder for morning filter brews.',
        price: 345,
        url: 'https://fellowproducts.com',
        category: 'Kitchen & Home',
        addedBy: { id: 'p-sarah-m', name: 'Sarah Chen' },
        forParticipantId: 'p-sarah-m',
        createdAt: '2026-09-22T07:26:00.000Z',
        isGroupGift: true,
        status: 'sharing',
        reactions: [
          { id: 'r-5', type: 'love', participantId: 'p-n2czl2t', participantName: 'Noel' },
        ],
        contributions: [
          {
            id: 'c-3',
            participantId: 'p-n2czl2t',
            participantName: 'Noel',
            amount: 80,
            note: 'Willing to share this group coffee gift!',
            createdAt: '2026-09-22T07:42:00.000Z',
          },
        ],
      },
      {
        id: 'g-sarah-2',
        title: 'Kinto Ceramic Mug (Warm Moss Green, 320ml)',
        description: 'Handmade tactile glaze with comfortable handle.',
        price: 26,
        category: 'Kitchen & Home',
        addedBy: { id: 'p-sarah-m', name: 'Sarah Chen' },
        forParticipantId: 'p-sarah-m',
        createdAt: '2026-09-22T07:28:00.000Z',
        isGroupGift: false,
        status: 'prepared',
        preparedBy: {
          participantId: 'p-liam-k',
          participantName: 'Liam Vance',
          preparedAt: '2026-09-22T07:44:00.000Z',
          note: 'Got this wrapped in ribbon!',
        },
        reactions: [
          { id: 'r-6', type: 'check', participantId: 'p-liam-k', participantName: 'Liam Vance' },
        ],
        contributions: [],
      },
      {
        id: 'g-sarah-3',
        title: 'Hardcover Copy: "A Gentleman in Moscow"',
        description: 'Deluxe anniversary deckle-edge edition.',
        price: 32,
        category: 'Books & Stationery',
        addedBy: { id: 'p-sarah-m', name: 'Sarah Chen' },
        forParticipantId: 'p-sarah-m',
        createdAt: '2026-09-22T07:29:00.000Z',
        isGroupGift: false,
        status: 'open',
        reactions: [],
        contributions: [],
      },
      // Liam's wishlist
      {
        id: 'g-liam-1',
        title: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
        description: 'Fully aluminum body with banana tactile switches.',
        price: 199,
        category: 'Tech & Desk',
        addedBy: { id: 'p-liam-k', name: 'Liam Vance' },
        forParticipantId: 'p-liam-k',
        createdAt: '2026-09-22T07:31:00.000Z',
        isGroupGift: true,
        status: 'open',
        reactions: [
          { id: 'r-7', type: 'idea', participantId: 'p-n2czl2t', participantName: 'Noel' },
        ],
        contributions: [],
      },
      {
        id: 'g-liam-2',
        title: 'Black Diamond Storm 500-R Headlamp',
        description: 'Rechargeable waterproof headlamp for night trail running.',
        price: 75,
        category: 'Garden & Outdoor',
        addedBy: { id: 'p-liam-k', name: 'Liam Vance' },
        forParticipantId: 'p-liam-k',
        createdAt: '2026-09-22T07:32:00.000Z',
        isGroupGift: false,
        status: 'prepared',
        preparedBy: {
          participantId: 'p-n2czl2t',
          participantName: 'Noel',
          preparedAt: '2026-09-22T07:45:00.000Z',
          note: 'Prepared and ready to gift!',
        },
        reactions: [
          { id: 'r-8', type: 'check', participantId: 'p-n2czl2t', participantName: 'Noel' },
        ],
        contributions: [],
      },
      {
        id: 'g-liam-3',
        title: 'Merino Wool Trail Running Socks (3-Pack, Charcoal)',
        description: 'Cushioned crew height, anti-blister.',
        price: 45,
        category: 'Style & Accessories',
        addedBy: { id: 'p-liam-k', name: 'Liam Vance' },
        forParticipantId: 'p-liam-k',
        createdAt: '2026-09-22T07:33:00.000Z',
        isGroupGift: false,
        status: 'open',
        reactions: [],
        contributions: [],
      },
      // Chloe's wishlist
      {
        id: 'g-chloe-1',
        title: 'Audio-Technica LP60XBT Bluetooth Turntable',
        description: 'Compact automatic turntable in white.',
        price: 219,
        category: 'Tech & Desk',
        addedBy: { id: 'p-chloe-b', name: 'Chloe Bennett' },
        forParticipantId: 'p-chloe-b',
        createdAt: '2026-09-22T07:34:00.000Z',
        isGroupGift: true,
        status: 'sharing',
        reactions: [
          { id: 'r-9', type: 'excited', participantId: 'p-sarah-m', participantName: 'Sarah Chen' },
          { id: 'r-10', type: 'love', participantId: 'p-liam-k', participantName: 'Liam Vance' },
        ],
        contributions: [
          {
            id: 'c-4',
            participantId: 'p-liam-k',
            participantName: 'Liam Vance',
            amount: 60,
            note: 'Vinyl lover here, happy to chip in!',
            createdAt: '2026-09-22T07:46:00.000Z',
          },
        ],
      },
      {
        id: 'g-chloe-2',
        title: 'Handmade Stoneware Pouring Bowl & Whisk',
        description: 'For mixing matcha and ceramics glaze testing.',
        price: 42,
        category: 'Keepsake & Handmade',
        addedBy: { id: 'p-chloe-b', name: 'Chloe Bennett' },
        forParticipantId: 'p-chloe-b',
        createdAt: '2026-09-22T07:36:00.000Z',
        isGroupGift: false,
        status: 'open',
        reactions: [],
        contributions: [],
      },
    ],
  },
  {
    id: 'moms-60th-birthday',
    title: "Mom's 60th Birthday",
    tagline: 'A milestone celebration for Eleanor! Let’s coordinate something truly unforgettable.',
    type: 'celebration',
    occasion: 'Birthday',
    recipientName: 'Mom (Eleanor)',
    organizerName: 'Sarah',
    organizerKeyword: 'daisy60',
    currency: '$',
    createdAt: '2026-09-10T14:30:00.000Z',
    targetDate: '2026-10-15',
    participants: [
      {
        id: 'p-sarah',
        name: 'Sarah (Organizer)',
        keyword: 'daisy60',
        avatarColor: 'bg-[#5C1525]',
        isOrganizer: true,
        joinedAt: '2026-09-10T14:30:00.000Z',
      },
      {
        id: 'p-robert',
        name: 'Dad (Robert)',
        keyword: 'garden22',
        avatarColor: 'bg-[#8F5D38]',
        joinedAt: '2026-09-11T09:15:00.000Z',
      },
      {
        id: 'p-michael',
        name: 'Michael (Brother)',
        keyword: 'hiking99',
        avatarColor: 'bg-[#3A5A40]',
        joinedAt: '2026-09-11T11:40:00.000Z',
      },
      {
        id: 'p-claire',
        name: 'Aunt Claire',
        keyword: 'baking44',
        avatarColor: 'bg-[#741D30]',
        joinedAt: '2026-09-12T16:20:00.000Z',
      },
    ],
    gifts: [
      {
        id: 'g-101',
        title: 'Le Creuset Enameled Cast Iron Dutch Oven (5.5 Qt, Cerise Red)',
        description: 'Mom has been eyeing this heirloom piece for her Sunday sourdough and winter beef bourguignon.',
        price: 420,
        url: 'https://lecreuset.com',
        category: 'Kitchen & Home',
        addedBy: { id: 'p-sarah', name: 'Sarah' },
        createdAt: '2026-09-11T10:00:00.000Z',
        isGroupGift: true,
        status: 'sharing',
        reactions: [
          { id: 'r-11', type: 'love', participantId: 'p-robert', participantName: 'Dad (Robert)' },
          { id: 'r-12', type: 'excited', participantId: 'p-claire', participantName: 'Aunt Claire' },
        ],
        contributions: [
          {
            id: 'c-10',
            participantId: 'p-robert',
            participantName: 'Dad (Robert)',
            amount: 150,
            note: 'Count me in for a major share!',
            createdAt: '2026-09-11T11:00:00.000Z',
          },
          {
            id: 'c-11',
            participantId: 'p-sarah',
            participantName: 'Sarah',
            amount: 120,
            note: 'I will handle the boutique gift wrapping!',
            createdAt: '2026-09-11T11:30:00.000Z',
          },
          {
            id: 'c-12',
            participantId: 'p-claire',
            participantName: 'Aunt Claire',
            amount: 75,
            note: 'So thrilled for this!',
            createdAt: '2026-09-12T17:00:00.000Z',
          },
        ],
      },
      {
        id: 'g-102',
        title: 'Weekend Spa Retreat at Miraval Berkshires',
        description: '2-night restorative wellness escape with farm-to-table culinary dinners.',
        price: 850,
        url: 'https://miravalresorts.com',
        category: 'Experiences',
        addedBy: { id: 'p-michael', name: 'Michael (Brother)' },
        createdAt: '2026-09-11T12:00:00.000Z',
        isGroupGift: true,
        status: 'open',
        reactions: [
          { id: 'r-13', type: 'love', participantId: 'p-sarah', participantName: 'Sarah' },
          { id: 'r-14', type: 'idea', participantId: 'p-michael', participantName: 'Michael' },
        ],
        contributions: [
          {
            id: 'c-13',
            participantId: 'p-michael',
            participantName: 'Michael',
            amount: 250,
            note: 'Can split the balance with others.',
            createdAt: '2026-09-11T12:30:00.000Z',
          },
        ],
      },
    ],
    notes: [
      {
        id: 'note-1',
        category: 'dislike',
        content: "Mom really doesn't like black or dark grey colors — she loves warm tones, soft olive, terracotta, or cerise red!",
        addedBy: { id: 'p-michael', name: 'Michael (Brother)' },
        createdAt: '2026-09-12T10:00:00.000Z',
        isImportant: true,
      },
      {
        id: 'note-2',
        category: 'allergy',
        content: 'Mom is allergic to strong synthetic lavender fragrances and heavily perfumed lotions (gentle citrus & vanilla are fine).',
        addedBy: { id: 'p-sarah', name: 'Sarah (Organizer)' },
        createdAt: '2026-09-11T15:30:00.000Z',
        isImportant: true,
      },
      {
        id: 'note-3',
        category: 'already_bought',
        content: 'Aunt Claire already ordered her a cashmere gardening scarf and gloves, so please avoid getting winter accessories.',
        addedBy: { id: 'p-claire', name: 'Aunt Claire' },
        createdAt: '2026-09-13T12:00:00.000Z',
        isImportant: false,
      },
      {
        id: 'note-4',
        category: 'preference',
        content: "Shoe size is 7.5 US, and ring size is 6. She's been wanting to expand her kitchen herb garden!",
        addedBy: { id: 'p-robert', name: 'Dad (Robert)' },
        createdAt: '2026-09-13T14:15:00.000Z',
        isImportant: false,
      },
    ],
  },
];
